---
switches: 
  - {hostname: pynet-sw1, secret: <secret>, ip_addr: 10.10.10.20, 
        default_gateway: 10.10.10.1, access_vlan: 10, snmp_community: <community>}
  - {hostname: pynet-sw2, secret: <secret>, ip_addr: 10.10.20.20, 
        default_gateway: 10.10.20.1, access_vlan: 20, snmp_community: <community>}
  - {hostname: pynet-sw3, secret: <secret>, ip_addr: 10.10.30.20, 
        default_gateway: 10.10.30.1, access_vlan: 30, snmp_community: <community>}
  - {hostname: pynet-sw4, secret: <secret>, ip_addr: 10.10.40.20, 
        default_gateway: 10.10.40.1, access_vlan: 40, snmp_community: <community>}
  - {hostname: pynet-sw5, secret: <secret>, ip_addr: 10.10.50.20, 
        default_gateway: 10.10.50.1, access_vlan: 50, snmp_community: <community>}


